### ISSUE TITLE
RuntimeError: Error compiling objects for extension

### ISSUE THREAD

**Issue by xiaoli-ai** [sshaoshuai/Pointnet2.PyTorch#19]
您好，我的环境是：
ubuntu16.04
torch1.5
cuda10.1
我的编译一直不能正常通过，报错信息如下：
[9/9] /usr/local/cuda-10.1/bin/nvcc -I/home/psdz/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/include -I/home/psdz/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/psdz/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/TH -I/home/psdz/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-10.1/include -I/home/psdz/anaconda3/envs/pytorch/include/python3.8 -c -c '/home/psdz/文档/Pointnet2.PyTorch/pointnet2/src/sampling_gpu.cu' -o '/home/psdz/文档/Pointnet2.PyTorch/pointnet2/build/temp.linux-x86_64-3.8/src/sampling_gpu.o' -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -O2 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=pointnet2_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -std=c++14
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/psdz/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1395, in _run_ninja_build
    subprocess.run(
  File "/home/psdz/anaconda3/envs/pytorch/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    setup(
  File "/home/psdz/anaconda3/envs/pytorch/lib/python3.8/site-packages/setuptools/__init__.py", line 161, in setup
    return distutils.core.setup(**attrs)
  File "/home/psdz/anaconda3/envs/pytorch/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/psdz/anaconda3/envs/pytorch/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/psdz/anaconda3/envs/pytorch/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/psdz/anaconda3/envs/pytorch/lib/python3.8/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/psdz/anaconda3/envs/pytorch/lib/python3.8/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/psdz/anaconda3/envs/pytorch/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/psdz/anaconda3/envs/pytorch/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/psdz/anaconda3/envs/pytorch/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 173, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/psdz/anaconda3/envs/pytorch/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 159, in call_command
    self.run_command(cmdname)
  File "/home/psdz/anaconda3/envs/pytorch/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/psdz/anaconda3/envs/pytorch/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/psdz/anaconda3/envs/pytorch/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/psdz/anaconda3/envs/pytorch/lib/python3.8/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/psdz/anaconda3/envs/pytorch/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/psdz/anaconda3/envs/pytorch/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/psdz/anaconda3/envs/pytorch/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 87, in run
    _build_ext.run(self)
  File "/home/psdz/anaconda3/envs/pytorch/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/home/psdz/anaconda3/envs/pytorch/lib/python3.8/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/psdz/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 580, in build_extensions
    build_ext.build_extensions(self)
  File "/home/psdz/anaconda3/envs/pytorch/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/home/psdz/anaconda3/envs/pytorch/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/psdz/anaconda3/envs/pytorch/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/psdz/anaconda3/envs/pytorch/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 208, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/psdz/anaconda3/envs/pytorch/lib/python3.8/distutils/command/build_ext.py", line 528, in build_extension
    objects = self.compiler.compile(sources,
  File "/home/psdz/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 414, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/home/psdz/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1135, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/home/psdz/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1413, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension
请指导一下，谢谢您

**Comment by swwzn714** [comment]
一样的问题

**Comment by Abrascha** [comment]
see here: https://github.com/hyangwinter/flownet3d_pytorch/issues/8#issuecomment-663925414

**Comment by lmw0320** [comment]
@xiaoli-ai @xiaobiaozhu  请问您解决了么？
我的环境是Ubuntu18.04, cuda10.1， pytorch1.6.0+cu101, py3.6, 前面的fvcore,cython, pycocotools什么的，都成功安装了的。。就是编译这个detectron2，一直报错，情况和您的一样，至今没法解决。。
我看三楼这位提供的参考情况，但是我看不太懂这里的链接情况，感觉说得很乱，都不知道具体要如何解决。

**Comment by Abrascha** [comment]
@lmw0320 
照着这句话做，把库里函数名替换掉，应该是版本升级改了函数名称
I replaced all mentions of AT_CHECK and THCState_getCurrentStream(state) with TORCH_CHECK and at::cuda::getCurrentCUDAStream(), respectively. I was then able to install setup.py without errors. Thank you for your help!

**Comment by Sherlock-hh** [comment]
请问是修改哪个文件下的部分呢？主要是我用python3.8 pytorch7.1成功编译了，但是python3.7和pytorch1.7.1一直编不过，但是环境又要求是python3.7

**Comment by youkangGG** [comment]
> 请问是修改哪个文件下的部分呢？主要是我用python3.8 pytorch7.1成功编译了，但是python3.7和pytorch1.7.1一直编不过，但是环境又要求是python3.7

./pointnet2/src/ 里的那些.cpp .h .cu文件。替换掉这些文件中所有使用AT_CHECK和THCState_getCurrentStream(state)的地方就好。

**Comment by Sherlock-hh** [comment]
谢谢回复！我打开这些源码后发现代码的都是已经修改好了的，不过我发现我用的是pytorch1.7，我换回1.6就能编译了。
版本太新了😂

---Original---

**Comment by liyabo123456** [comment]
你好你的那个问题是如何解决我的有点不明白

**Comment by wangat** [comment]
> > 请问是修改哪个文件下的部分呢？主要是我用python3.8 pytorch7.1成功编译了，但是python3.7和pytorch1.7.1一直编不过，但是环境又要求是python3.7
> 
> ./pointnet2/src/ 里的那些.cpp .h .cu文件。替换掉这些文件中所有使用AT_CHECK和THCState_getCurrentStream(state)的地方就好。

您好，我在配置SE-SSD环境也遇到了这个问题，按照您说的内容，修改这些文件，发现AT_CHECK需要修改，THCState_getCurrentStream(state)已经都是at::cuda::getCurrentCUDAStream()，但是修改后测试还是报了相同的错误
