### ISSUE TITLE
RuntimeError: Error compiling objects for extension

### ISSUE THREAD

**Issue by theycallmefm** [sshaoshuai/Pointnet2.PyTorch#22]
Hi, I can't install library. I am new to compiling C++ code using Python. Is there a way to compile using my settings?

```
running install
running bdist_egg
running egg_info
writing pointnet2.egg-info/PKG-INFO
writing dependency_links to pointnet2.egg-info/dependency_links.txt
writing top-level names to pointnet2.egg-info/top_level.txt
reading manifest file 'pointnet2.egg-info/SOURCES.txt'
writing manifest file 'pointnet2.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
building 'pointnet2_cuda' extension
Emitting ninja build file /net/coxfs01/srv/export/coxfs01/pfister_lab2/share_root/Lab/theycallmefm/flownet3d_pytorch/lib/build/temp.linux-x86_64-3.6/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/8] g++ -MMD -MF /net/coxfs01/srv/export/coxfs01/pfister_lab2/share_root/Lab/theycallmefm/flownet3d_pytorch/lib/build/temp.linux-x86_64-3.6/src/ball_query.o.d -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include -I/n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include/TH -I/n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include/THC -I/n/helmod/apps/centos7/Core/cuda/10.2.89-fasrc01/cuda/include -I/n/helmod/apps/centos7/CUDA/cuda/10.2.89-fasrc01/cudnn/7.6.5.32_cuda10.2-fasrc01/include -I/n/home03/theycallmefm/.conda/envs/flownet3d/include/python3.6m -c -c /net/coxfs01/srv/export/coxfs01/pfister_lab2/share_root/Lab/theycallmefm/flownet3d_pytorch/lib/src/ball_query.cpp -o /net/coxfs01/srv/export/coxfs01/pfister_lab2/share_root/Lab/theycallmefm/flownet3d_pytorch/lib/build/temp.linux-x86_64-3.6/src/ball_query.o -g -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=pointnet2_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
FAILED: /net/coxfs01/srv/export/coxfs01/pfister_lab2/share_root/Lab/theycallmefm/flownet3d_pytorch/lib/build/temp.linux-x86_64-3.6/src/ball_query.o 
g++ -MMD -MF /net/coxfs01/srv/export/coxfs01/pfister_lab2/share_root/Lab/theycallmefm/flownet3d_pytorch/lib/build/temp.linux-x86_64-3.6/src/ball_query.o.d -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include -I/n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include/TH -I/n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include/THC -I/n/helmod/apps/centos7/Core/cuda/10.2.89-fasrc01/cuda/include -I/n/helmod/apps/centos7/CUDA/cuda/10.2.89-fasrc01/cudnn/7.6.5.32_cuda10.2-fasrc01/include -I/n/home03/theycallmefm/.conda/envs/flownet3d/include/python3.6m -c -c /net/coxfs01/srv/export/coxfs01/pfister_lab2/share_root/Lab/theycallmefm/flownet3d_pytorch/lib/src/ball_query.cpp -o /net/coxfs01/srv/export/coxfs01/pfister_lab2/share_root/Lab/theycallmefm/flownet3d_pytorch/lib/build/temp.linux-x86_64-3.6/src/ball_query.o -g -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=pointnet2_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include/ATen/Parallel.h:149,
                 from /n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include/TH/THTensorApply.h:4,
                 from /n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include/TH/THTensor.h:5,
                 from /n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include/THC/THCTensor.h:4,
                 from /n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include/THC/THC.h:13,
                 from /net/coxfs01/srv/export/coxfs01/pfister_lab2/share_root/Lab/theycallmefm/flownet3d_pytorch/lib/src/ball_query.cpp:3:
/n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include/ATen/ParallelOpenMP.h:84: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
   84 | #pragma omp parallel for if ((end - begin) >= grain_size)
      | 
/net/coxfs01/srv/export/coxfs01/pfister_lab2/share_root/Lab/theycallmefm/flownet3d_pytorch/lib/src/ball_query.cpp: In function ‘int ball_query_wrapper_fast(int, int, int, float, int, at::Tensor, at::Tensor, at::Tensor)’:
/net/coxfs01/srv/export/coxfs01/pfister_lab2/share_root/Lab/theycallmefm/flownet3d_pytorch/lib/src/ball_query.cpp:10:39: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
   10 | #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
      |                                       ^
/net/coxfs01/srv/export/coxfs01/pfister_lab2/share_root/Lab/theycallmefm/flownet3d_pytorch/lib/src/ball_query.cpp:12:24: note: in expansion of macro ‘CHECK_CUDA’
   12 | #define CHECK_INPUT(x) CHECK_CUDA(x);CHECK_CONTIGUOUS(x)
      |                        ^~~~~~~~~~
/net/coxfs01/srv/export/coxfs01/pfister_lab2/share_root/Lab/theycallmefm/flownet3d_pytorch/lib/src/ball_query.cpp:16:5: note: in expansion of macro ‘CHECK_INPUT’
   16 |     CHECK_INPUT(new_xyz_tensor);
      |     ^~~~~~~~~~~
In file included from /n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include/ATen/Tensor.h:3,
                 from /n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include/ATen/Context.h:4,
                 from /n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include/ATen/ATen.h:5,
                 from /n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/serialize/input-archive.h:6,
                 from /n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/serialize/archive.h:3,
                 from /n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/serialize/tensor.h:3,
                 from /net/coxfs01/srv/export/coxfs01/pfister_lab2/share_root/Lab/theycallmefm/flownet3d_pytorch/lib/src/ball_query.cpp:1:
/n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include/ATen/core/TensorBody.h:268:30: note: declared here
  268 |   DeprecatedTypeProperties & type() const {
      |                              ^~~~
/net/coxfs01/srv/export/coxfs01/pfister_lab2/share_root/Lab/theycallmefm/flownet3d_pytorch/lib/src/ball_query.cpp:10:23: error: ‘AT_CHECK’ was not declared in this scope; did you mean ‘DCHECK’?
   10 | #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
      |                       ^~~~~~~~
/net/coxfs01/srv/export/coxfs01/pfister_lab2/share_root/Lab/theycallmefm/flownet3d_pytorch/lib/src/ball_query.cpp:10:23: note: in definition of macro ‘CHECK_CUDA’
   10 | #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
      |                       ^~~~~~~~
/net/coxfs01/srv/export/coxfs01/pfister_lab2/share_root/Lab/theycallmefm/flownet3d_pytorch/lib/src/ball_query.cpp:16:5: note: in expansion of macro ‘CHECK_INPUT’
   16 |     CHECK_INPUT(new_xyz_tensor);
      |     ^~~~~~~~~~~
/net/coxfs01/srv/export/coxfs01/pfister_lab2/share_root/Lab/theycallmefm/flownet3d_pytorch/lib/src/ball_query.cpp:10:39: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
   10 | #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
      |                                       ^
/net/coxfs01/srv/export/coxfs01/pfister_lab2/share_root/Lab/theycallmefm/flownet3d_pytorch/lib/src/ball_query.cpp:12:24: note: in expansion of macro ‘CHECK_CUDA’
   12 | #define CHECK_INPUT(x) CHECK_CUDA(x);CHECK_CONTIGUOUS(x)
      |                        ^~~~~~~~~~
/net/coxfs01/srv/export/coxfs01/pfister_lab2/share_root/Lab/theycallmefm/flownet3d_pytorch/lib/src/ball_query.cpp:17:5: note: in expansion of macro ‘CHECK_INPUT’
   17 |     CHECK_INPUT(xyz_tensor);
      |     ^~~~~~~~~~~
In file included from /n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include/ATen/Tensor.h:3,
                 from /n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include/ATen/Context.h:4,
                 from /n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include/ATen/ATen.h:5,
                 from /n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/serialize/input-archive.h:6,
                 from /n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/serialize/archive.h:3,
                 from /n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/serialize/tensor.h:3,
                 from /net/coxfs01/srv/export/coxfs01/pfister_lab2/share_root/Lab/theycallmefm/flownet3d_pytorch/lib/src/ball_query.cpp:1:
/n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include/ATen/core/TensorBody.h:268:30: note: declared here
  268 |   DeprecatedTypeProperties & type() const {
      |                              ^~~~
/net/coxfs01/srv/export/coxfs01/pfister_lab2/share_root/Lab/theycallmefm/flownet3d_pytorch/lib/src/ball_query.cpp:18:55: warning: ‘T* at::Tensor::data() const [with T = float]’ is deprecated: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead. [-Wdeprecated-declarations]
   18 |     const float *new_xyz = new_xyz_tensor.data<float>();
      |                                                       ^
In file included from /n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include/ATen/Tensor.h:3,
                 from /n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include/ATen/Context.h:4,
                 from /n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include/ATen/ATen.h:5,
                 from /n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/serialize/input-archive.h:6,
                 from /n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/serialize/archive.h:3,
                 from /n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/serialize/tensor.h:3,
                 from /net/coxfs01/srv/export/coxfs01/pfister_lab2/share_root/Lab/theycallmefm/flownet3d_pytorch/lib/src/ball_query.cpp:1:
/n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include/ATen/core/TensorBody.h:354:7: note: declared here
  354 |   T * data() const {
      |       ^~~~
/net/coxfs01/srv/export/coxfs01/pfister_lab2/share_root/Lab/theycallmefm/flownet3d_pytorch/lib/src/ball_query.cpp:19:47: warning: ‘T* at::Tensor::data() const [with T = float]’ is deprecated: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead. [-Wdeprecated-declarations]
   19 |     const float *xyz = xyz_tensor.data<float>();
      |                                               ^
In file included from /n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include/ATen/Tensor.h:3,
                 from /n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include/ATen/Context.h:4,
                 from /n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include/ATen/ATen.h:5,
                 from /n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/serialize/input-archive.h:6,
                 from /n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/serialize/archive.h:3,
                 from /n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/serialize/tensor.h:3,
                 from /net/coxfs01/srv/export/coxfs01/pfister_lab2/share_root/Lab/theycallmefm/flownet3d_pytorch/lib/src/ball_query.cpp:1:
/n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include/ATen/core/TensorBody.h:354:7: note: declared here
  354 |   T * data() const {
      |       ^~~~
/net/coxfs01/srv/export/coxfs01/pfister_lab2/share_root/Lab/theycallmefm/flownet3d_pytorch/lib/src/ball_query.cpp:20:37: warning: ‘T* at::Tensor::data() const [with T = int]’ is deprecated: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead. [-Wdeprecated-declarations]
   20 |     int *idx = idx_tensor.data<int>();
      |                                     ^
In file included from /n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include/ATen/Tensor.h:3,
                 from /n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include/ATen/Context.h:4,
                 from /n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include/ATen/ATen.h:5,
                 from /n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/serialize/input-archive.h:6,
                 from /n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/serialize/archive.h:3,
                 from /n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/serialize/tensor.h:3,
                 from /net/coxfs01/srv/export/coxfs01/pfister_lab2/share_root/Lab/theycallmefm/flownet3d_pytorch/lib/src/ball_query.cpp:1:
/n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include/ATen/core/TensorBody.h:354:7: note: declared here
  354 |   T * data() const {
      |       ^~~~
/net/coxfs01/srv/export/coxfs01/pfister_lab2/share_root/Lab/theycallmefm/flownet3d_pytorch/lib/src/ball_query.cpp:22:27: error: ‘THCState_getCurrentStream’ was not declared in this scope
   22 |     cudaStream_t stream = THCState_getCurrentStream(state);
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~
[2/8] g++ -MMD -MF /net/coxfs01/srv/export/coxfs01/pfister_lab2/share_root/Lab/theycallmefm/flownet3d_pytorch/lib/build/temp.linux-x86_64-3.6/src/pointnet2_api.o.d -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include -I/n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include/TH -I/n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include/THC -I/n/helmod/apps/centos7/Core/cuda/10.2.89-fasrc01/cuda/include -I/n/helmod/apps/centos7/CUDA/cuda/10.2.89-fasrc01/cudnn/7.6.5.32_cuda10.2-fasrc01/include -I/n/home03/theycallmefm/.conda/envs/flownet3d/include/python3.6m -c -c /net/coxfs01/srv/export/coxfs01/pfister_lab2/share_root/Lab/theycallmefm/flownet3d_pytorch/lib/src/pointnet2_api.cpp -o /net/coxfs01/srv/export/coxfs01/pfister_lab2/share_root/Lab/theycallmefm/flownet3d_pytorch/lib/build/temp.linux-x86_64-3.6/src/pointnet2_api.o -g -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=pointnet2_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include/ATen/Parallel.h:149,
                 from /n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/utils.h:3,
                 from /n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:5,
                 from /n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/nn.h:3,
                 from /n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/all.h:7,
                 from /n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include/torch/extension.h:4,
                 from /net/coxfs01/srv/export/coxfs01/pfister_lab2/share_root/Lab/theycallmefm/flownet3d_pytorch/lib/src/pointnet2_api.cpp:2:
/n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/include/ATen/ParallelOpenMP.h:84: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
   84 | #pragma omp parallel for if ((end - begin) >= grain_size)
      | 
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1515, in _run_ninja_build
    env=env)
  File "/n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 22, in <module>
    cmdclass={'build_ext': BuildExtension}
  File "/n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/setuptools/__init__.py", line 165, in setup
    return distutils.core.setup(**attrs)
  File "/n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 174, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 160, in call_command
    self.run_command(cmdname)
  File "/n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 87, in run
    _build_ext.run(self)
  File "/n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 649, in build_extensions
    build_ext.build_extensions(self)
  File "/n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 208, in build_extension
    _build_ext.build_extension(self, ext)
  File "/n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 478, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1233, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/n/home03/theycallmefm/.conda/envs/flownet3d/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1529, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension
```

My settings: 
Python 3.6.10 
GCC 9.3.0
CUDA 10.2
Pytorch 1.6.0

**Comment by theycallmefm** [comment]
For anyone wondering, I followed these steps and it worked. https://github.com/hyangwinter/flownet3d_pytorch/issues/8
