### ISSUE TITLE
.so: undefined symbol

### ISSUE THREAD

**Issue by 635583042qq** [sshaoshuai/Pointnet2.PyTorch#36]
when ℹ run this command :python train_and_eval.py --batch_size 8 --epochs 100 --ckpt_save_interval 2 
i get error :Traceback (most recent call last):
  File "train_and_eval.py", line 183, in <module>
    MODEL = importlib.import_module(args.net)  # import network module
  File "/home/liyunhao/anaconda3/envs/pointnet2/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/liyunhao/bao/Pointnet2.PyTorch-master/tools/pointnet2_msg.py", line 3, in <module>
    from pointnet2.pointnet2_modules import PointnetFPModule, PointnetSAModuleMSG
  File "/home/liyunhao/bao/Pointnet2.PyTorch-master/tools/../pointnet2/pointnet2_modules.py", line 5, in <module>
    from . import pointnet2_utils
  File "/home/liyunhao/bao/Pointnet2.PyTorch-master/tools/../pointnet2/pointnet2_utils.py", line 7, in <module>
    import pointnet2_cuda as pointnet2
ImportError: /home/liyunhao/anaconda3/envs/pointnet2/lib/python3.7/site-packages/pointnet2-0.0.0-py3.7-linux-x86_64.egg/pointnet2_cuda.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _Z31gather_points_grad_wrapper_fastiiiiN2at6TensorES0_S0_

I think this error has something to do with so file but i cant solve it .

**Comment by Dejavuvvw** [comment]
Hello, I also encountered the same problem. Have you solved it?

**Comment by jia1047** [comment]
请问解决了吗?显示装上了链接库,但是import pointnet2_cuda as pointnet2,pointnet2.ball_query_wrapper(B, N, npoint, radius, nsample, new_xyz, xyz, idx)有问题,查找不到pointnet2.ball_query_wrapper()
